/**
 * OpenAPI definition
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { DistrictDTO } from './districtDTO';

export interface CityDTO {
    name?: string;
    districtDTOS?: Array<String>;

}

export class City implements CityDTO{
  name?: string;
  districtDTOS?: Array<String>;
  constructor(name: string, districtDTOS: Array<String>) {
    this.name = name;
    this.districtDTOS = districtDTOS;
  }
}
